// 공통
// status: ing, done, deploy, delete

const job00Common = [
  {
    listStart: true,
    depth1: '',
    depth2: '',
    depth3: '',
    depth4: '',
    depth5: '',
    depth6: '',
    type: '',
    page: 'page',
    url: '',
    startDate: '',
    endDate: '',
    finalDate: '',
    dueDate: '',
    status: 'done',
    worker: '강수민',
    memos: ['IA_TEST'],
  },
  {
    listStart: true,
    depth1: '',
    depth2: '',
    depth3: '',
    depth4: '',
    depth5: '',
    depth6: '',
    type: '',
    page: '',
    url: '',
    startDate: '',
    endDate: '',
    finalDate: '',
    dueDate: '',
    status: '',
    worker: '',
    memos: [''],
  },
  {
    listStart: true,
    depth1: '',
    depth2: '',
    depth3: '',
    depth4: '',
    depth5: '',
    depth6: '',
    type: '',
    page: '',
    url: '',
    startDate: '',
    endDate: '',
    finalDate: '',
    dueDate: '',
    status: '',
    worker: '',
    memos: [''],
  },
  {
    listStart: true,
    depth1: '',
    depth2: '',
    depth3: '',
    depth4: '',
    depth5: '',
    depth6: '',
    type: '',
    page: '',
    url: '',
    startDate: '',
    endDate: '',
    finalDate: '',
    dueDate: '',
    status: '',
    worker: '',
    memos: [''],
  },
  {
    listStart: true,
    depth1: '',
    depth2: '',
    depth3: '',
    depth4: '',
    depth5: '',
    depth6: '',
    type: '',
    page: '',
    url: '',
    startDate: '',
    endDate: '',
    finalDate: '',
    dueDate: '',
    status: '',
    worker: '',
    memos: [''],
  },
]

export default job00Common
